
[build]
  command = "npm ci && npm run build:clean"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_VERSION = "9.6.7"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --prefer-offline"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"

[build.processing]
  skip_processing = true

[functions]
  included_files = ["node_modules/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
